# Generated by Django 4.2.1 on 2023-05-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_children', to='familytree.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_father', to='familytree.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_mother', to='familytree.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_siblings', to='familytree.person'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('spouse', 'Spouse')], max_length=20),
        ),
    ]
