# Generated by Django 4.2.1 on 2023-05-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_person_children_alter_person_father_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='children',
        ),
    ]
