# Generated by Django 4.2.1 on 2023-05-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_remove_person_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='siblings',
        ),
    ]
