# Generated by Django 4.2.1 on 2023-06-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0006_remove_person_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='iwi',
            field=models.CharField(blank=True, choices=[('Northland/Auckland (Te Tai Tokerau/Tāmaki-makaurau)', (('Ngāi Tai ki Tāmaki', 'Ngāi Tai ki Tāmaki'), ('Ngāi Takoto', 'Ngāi Takoto'), ('Ngāpuhi', 'Ngāpuhi'), ('Ngāpuhi ki Whaingaroa-Ngāti Kahu ki Whaingaroa', 'Ngāpuhi ki Whaingaroa-Ngāti Kahu ki Whaingaroa'), ('Ngāti Hine (Te Tai Tokerau)', 'Ngāti Hine (Te Tai Tokerau)'), ('Ngāti Kahu', 'Ngāti Kahu'), ('Ngāti Kurī', 'Ngāti Kurī'), ('Ngāti Manuhiri', 'Ngāti Manuhiri'), ('Ngāti Rēhua', 'Ngāti Rēhua'), ('Ngāti Wai', 'Ngāti Wai'), ('Ngāti Whātua', 'Ngāti Whātua'), ('Ngāti Whātua o Kaipara', 'Ngāti Whātua o Kaipara'), ('Ngāti Whātua o Ōrākei', 'Ngāti Whātua o Ōrākei'), ('Te Aupōuri', 'Te Aupōuri'), ('Te Hiku collective', 'Te Hiku collective'), ('Te Kawerau ā Maki', 'Te Kawerau ā Maki'), ('Te Paatu', 'Te Paatu'), ('Te Rarawa', 'Te Rarawa'), ('Te Roroa', 'Te Roroa'), ('Te Uri-o-Hau', 'Te Uri-o-Hau')))], max_length=100, null=True),
        ),
    ]
