# Generated by Django 4.2.1 on 2023-06-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0008_alter_person_iwi_alter_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hapu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
