# Generated by Django 4.2.1 on 2023-06-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0009_person_hapu_alter_person_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='familytree.person')),
            ],
        ),
    ]
