# Generated by Django 4.2.1 on 2023-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0010_personmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmedia',
            name='alt_text',
            field=models.CharField(default='alt text', help_text='Provide alternative text for the image. Alt text is used by screen readers to describe the image for visually impaired users.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personmedia',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
