# Generated by Django 4.2.1 on 2023-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0011_personmedia_alt_text_personmedia_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmedia',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='personmedia',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Provide alternative text for the image. Alt text is used by screen readers to describe the image for visually impaired users.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personmedia',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
