# Generated by Django 4.2.1 on 2023-06-07 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0013_alter_person_iwi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmedia',
            options={'verbose_name_plural': 'person media'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='iwi',
        ),
        migrations.CreateModel(
            name='PersonIwi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('alt_text', models.CharField(blank=True, help_text='Provide alternative text for the image. Alt text is used by screen readers to describe the image for visually impaired users.', max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iwi', to='familytree.person')),
            ],
            options={
                'verbose_name_plural': 'person media',
            },
        ),
    ]
