# Generated by Django 4.2.1 on 2023-06-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0015_remove_personmedia_file_personmedia_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='familytree.person')),
            ],
        ),
    ]
