# Generated by Django 4.2.1 on 2023-06-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0017_alter_persondocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='familytree.person')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
            },
        ),
    ]
