# Generated by Django 4.2.1 on 2023-06-09 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0017_alter_persondocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondocument',
            options={'verbose_name': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='personhapu',
            options={'verbose_name_plural': 'Hapu'},
        ),
        migrations.AlterModelOptions(
            name='personiwi',
            options={'verbose_name_plural': 'Iwi'},
        ),
        migrations.AlterModelOptions(
            name='personmedia',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.CreateModel(
            name='PersonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Enter a YouTube video URL')),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='familytree.person')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
