# Generated by Django 4.2.1 on 2023-06-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0018_personvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personvideo',
            old_name='video',
            new_name='video_url',
        ),
    ]
