# Generated by Django 4.2.1 on 2023-06-09 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0019_rename_video_personvideo_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='familytree.person'),
        ),
    ]
