# Generated by Django 4.2.1 on 2023-06-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0019_persondocument_upload_date_personmedia_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personvideo',
            name='video_service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personvideo',
            name='video_url',
            field=models.URLField(help_text='Supports links from YouTube or Vimeo like https://www.youtube.com/watch?v=dQw4w9WgXcQ or https://vimeo.com/13020606'),
        ),
    ]
