# Generated by Django 4.2.1 on 2023-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0020_personvideo_video_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='maiden_name',
            field=models.CharField(blank=True, help_text='Enter the previous surname or any other name used before marriage. Leave this field blank if not applicable.', max_length=50, null=True),
        ),
    ]
