# Generated by Django 4.2.1 on 2023-06-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0020_alter_personvideo_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondocument',
            options={'verbose_name': 'Document'},
        ),
        migrations.AlterModelOptions(
            name='personhapu',
            options={'verbose_name_plural': 'Hapu'},
        ),
        migrations.AlterModelOptions(
            name='personiwi',
            options={'verbose_name_plural': 'Iwi'},
        ),
        migrations.AlterModelOptions(
            name='personmedia',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='personvideo',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
