# Generated by Django 4.2.1 on 2023-06-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0021_alter_persondocument_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='familytree.person'),
        ),
    ]
