# Generated by Django 4.2.1 on 2023-06-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0021_person_maiden_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whanau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('members', models.ManyToManyField(related_name='whanau', to='familytree.person')),
            ],
            options={
                'verbose_name_plural': 'Whanau',
            },
        ),
    ]
