# Generated by Django 4.2.1 on 2023-06-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0022_whanau'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauWaiata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='Supports links from YouTube or Vimeo like https://www.youtube.com/watch?v=dQw4w9WgXcQ or https://vimeo.com/13020606', null=True)),
                ('video_title', models.CharField(max_length=100)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('video_service', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('songwriter', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('lyrics', models.TextField(blank=True, max_length=2000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('whanau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiata', to='familytree.whanau')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
