# Generated by Django 4.2.1 on 2023-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0022_alter_personvideo_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='personvideo',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
