# Generated by Django 4.2.1 on 2023-06-09 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0023_personvideo_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideo',
            name='video_url',
            field=models.URLField(validators=[django.core.validators.URLValidator(message='Invalid YouTube video URL.')]),
        ),
    ]
