# Generated by Django 4.2.1 on 2023-06-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0023_whanauwaiata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personvideo',
            old_name='title',
            new_name='video_title',
        ),
        migrations.AlterField(
            model_name='personvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Supports links from YouTube or Vimeo like https://www.youtube.com/watch?v=dQw4w9WgXcQ or https://vimeo.com/13020606', null=True),
        ),
    ]
