# Generated by Django 4.2.1 on 2023-06-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0024_alter_personvideo_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideo',
            name='video_url',
            field=models.URLField(),
        ),
    ]
