# Generated by Django 4.2.1 on 2023-06-21 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0025_whanauhaka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whanauhaka',
            options={'verbose_name_plural': 'Haka'},
        ),
        migrations.AlterModelOptions(
            name='whanauwaiata',
            options={'verbose_name_plural': 'Waiata'},
        ),
    ]
