# Generated by Django 4.2.1 on 2023-06-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0026_alter_whanauhaka_options_alter_whanauwaiata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personvideo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='familytree.person'),
        ),
        migrations.CreateModel(
            name='WhanauImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text', models.CharField(help_text='Provide alternative text for the image. Alt text is used by screen readers to describe the image for visually impaired users.', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whanau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='familytree.whanau')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
    ]
