# Generated by Django 4.2.1 on 2023-06-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0027_alter_personvideo_person_whanauimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='Supports links from YouTube or Vimeo like https://www.youtube.com/watch?v=dQw4w9WgXcQ or https://vimeo.com/13020606', null=True)),
                ('video_title', models.CharField(max_length=100)),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
                ('video_service', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whanau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='familytree.whanau')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'abstract': False,
            },
        ),
    ]
