# Generated by Django 4.2.1 on 2023-06-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0029_whanauiwi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personhapu',
            options={'verbose_name': 'Hapu', 'verbose_name_plural': 'Hapu'},
        ),
        migrations.AlterModelOptions(
            name='personiwi',
            options={'verbose_name': 'Iwi', 'verbose_name_plural': 'Iwi'},
        ),
        migrations.AlterModelOptions(
            name='whanauiwi',
            options={'verbose_name': 'Iwi', 'verbose_name_plural': 'Iwi'},
        ),
    ]
