# Generated by Django 4.2.1 on 2023-06-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0030_alter_personhapu_options_alter_personiwi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauHapu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hapu', models.CharField(blank=True, max_length=100, null=True)),
                ('whanau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hapu', to='familytree.whanau')),
            ],
            options={
                'verbose_name': 'Hapu',
                'verbose_name_plural': 'Hapu',
            },
        ),
    ]
