# Generated by Django 4.2.1 on 2023-06-21 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0031_whanauhapu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondocument',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='familytree.person'),
        ),
        migrations.CreateModel(
            name='WhanauDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whanau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='familytree.whanau')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
    ]
