# Generated by Django 4.2.1 on 2023-06-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0032_alter_persondocument_person_whanaudocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whanauimage',
            options={},
        ),
    ]
