# Generated by Django 4.2.1 on 2023-06-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0034_whanaustory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauStoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_text', models.CharField(help_text='Provide alternative text for the image. Alt text is used by screen readers to describe the image for visually impaired users.', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whanau_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whanau_story_images', to='familytree.whanaustory')),
            ],
        ),
    ]
