# Generated by Django 4.2.1 on 2023-10-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0036_whanaustoryvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='whanaustoryvideo',
            name='title',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
