# Generated by Django 4.2.1 on 2023-10-15 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0037_whanaustoryvideo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whanaustoryvideo',
            name='upload_date',
        ),
    ]
