# Generated by Django 4.2.1 on 2023-10-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0039_remove_whanaustoryvideo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhanauStoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('whanau_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='familytree.whanaustory')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
    ]
